name: Comment on PR Commit

on:
  workflow_call:
    inputs:
      comment_message:
        description: "Message to post as comment"
        required: false
        default: "A commit has been pushed"

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              core.setFailed("Not a pull request event");
              return;
            }
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: inputs.comment_message
            });
